// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.msw.dao;

import com.msw.dao.FacturaRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FacturaRepository_Roo_Jpa_Repository {
    
    declare @type: FacturaRepository: @Transactional(readOnly = true);
    
}
